apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name  }}-configmap
  {{- template "mychart.systemlabels" $}}
data:
  myvalue: "Sample Config Map"
  costCode: {{ .Values.costCode }}
  Zone: {{ quote  .Values.infra.zone }}
  Region: {{ quote .Values.infra.region }}
  ProjectCode: {{ upper  .Values.projectCode }}
  pipeline: {{ .Values.projectCode | upper | quote  }}
  now: {{ now | date "2006-01-02" | quote  }}
  contact: {{ .Values.contact | default "1-800-123-0000" | quote }}

  {{- with .Values.tags.nova }}
  Machine Type: {{ .machine | default "NA" }}
  Rack ID: {{ .rack | quote }}
  Storage Type: {{ .drive | upper | quote }}
  Video Card: {{ .vcard | quote }}
  {{- end }}

  # Conditional Tests (Flow Test )
  # c_lt: {{ lt 1 2 }}
  # c_gt: {{ gt 1 2 }}
  # c_eq: {{ eq 1 2 }}
  # c_ne: {{ ne 1 2 }}
  # c_le: {{ le 1 2 }}
  # c_ge: {{ ge 1 2 }}

